### ISSUE TITLE
Interoperability with Seurat and comparison with traditional (clustered) DE analysis

### ISSUE THREAD

**Issue by learning-MD** [MarioniLab/miloDE#29]
Hi @amissarova,

As someone who has used miloR before, this looks like a great package that we are eager to explore more. I have a couple of questions I wanted to ask, if okay:

1. Is there a recommended dimensional reduction to use as an input when converting a Seurat object to SCE? We frequently use Harmony for integration/batch correction - should the Harmony embeddings be used? Or is it preferable to use the PCA embeddings without running Harmony? I've run a prelim ~150k dataset using the Harmony embeddings so far and am running a separate analysis looking the PCA alone. Any example code you may have would be appreciated.

2. Thanks for #27 - that has been very helpful in speeding up run times. At the moment, we are running `de_test_neighbourhoods` without pre-filtering out any neighborhoods. My understanding of the documentation is that this should not affect the output; just the runtime. Is that accurate?

3. In your design of this package, have you noticed any issues where there are minimal DEGs across clusters between disease and control but miloDE is able to identify genes/modules that are differentially expressed? We've noticed that with one of our datasets (~150k PBMCs) where pseudobulk analyses of our clusters (using limma-voom) results in essentially no DEGs between conditions. However, using the Harmony embeddings as input to miloDE resulted in DEGs and two modules using scWGCNA whose pathway analysis is biologically consistent with what we understand from animal studies. It was hard reconciling the drastic difference between cluster-dependent (traditional) and cluster-independent analyses. It may be that certain PBMCs (e.g., T cells) live in a more continuous cell state than the discrete clusters we annotated them as.

Thanks! Looking forward to using this package more often and re-running some of our old work with this to, perhaps, get better biological insight.

**Comment by mihem** [comment]
I (and I think many others) would be also very intersted in those answers, espeicially concerning the correct input.

An official response e.g. from @amissarova  would be greatly appreciated.

Based on answers from MikeDMorgan in miloR https://github.com/MarioniLab/miloR/issues/151, I think using harmony/integrated assay from Seurat would be the counterpart to pca.corrected that milo team uses in `assign_neighborhoods`. Correct?

I think it is confusing that miloDE uses different functions than miloR. So e.g. is `miloDE::assign_neighbourhoods` the same as `miloR::buildGraphs` and `miloR::makeNhoods` ?

One pitfall is that when you use the integrated (so batch corrected) input from Seurat with
`as.SingleCellExperiment(seu, assay = "integrated)` you only have a logcounts, but not a counts assay. This works fine for miloR, but does not work for miloDE, e.g. for `assign_neighbourhoods`.

Thanks!

**Comment by amissarova** [comment]
Hey @learning-MD and @mihem , thanks for your interest in the package. I'll try to answer to both lines of questions in one thread, pls let me know if something is unclear or if you have follow-up questions. 

1. Choice of dimensionality reduction.
We found that dimensionality reduction choice, at least for DE testing, matters and affects the sensitivity of the detection. We contemplate on this in the Supplementary Note, so if you are interested, please have a look here: https://www.biorxiv.org/content/10.1101/2023.03.08.531744v1.supplementary-material (Supplementary Note 1). 
The TLDR version of this note boils down to this. The ~‘continuous’ miloDE nature can run into a circular, self-contradictory conundrum: we use transcriptome to group cells together into transcriptionally ‘very similar’ cells, however, then we strive to find transcriptional differences between the cells. Practically this conundrum can be, at least partially, resolved if we define that case-specific variance can be decomposed in common (between case and control) variance (i.e. cell types) and case-only variance (i.e. disease genes), and therefore in miloDE we aim to detect case-only specific variance. In other words, crudely speaking, we can think of each gene contributing mainly to the common variance (i.e. cell type markers) or disease-specific variance. What this practically means, in terms of the embedding, is that you want the embedding that is originally constructed based on the control/shared variance, with case data being post-hoc ‘mapped’ onto the embedding (and therefore case variance doesn't contribute to the embedding and can be well detected with miloDE). Methods that are specifically tailored for this task fall into the category ‘supervised reference-based learning’, and the most commonly and successfully used methods (up to my knowledge) would be scArches and Azimuth mappings (fro Azimuth, good step-by-step manual can be found here https://satijalab.org/seurat/articles/integration_mapping.html ). Strictly speaking, MNN is an unsupervised approach however it would somewhat depend on the choice of genes you submit. Specifically, I recommend that if you use MNN, you ensure that your HVG selection is extracted using reference data only - thus you minimise the probability of selecting case-specific DE genes, and in this case the performance of miloDE likely to resemble supervise reference-based approaches. 
Specific to Harmony - unfortunately, I dont have the in-depth practical knowledge on how it would perform since I never tested it for miloDE. Theoretically, I can imagine that in Harmony disease-specific variance is likely to be treated as a batch effect and be corrected for (which is good for our cause actually). My concern however will lie with how Harmony might confuse real biological differences between replicates from the same condition with the batch effect, and this difference will be overlaid on top of the other in the embedding which might lead to misleading FPs (you detect some genes to be DE whereas they are actually more reference-specific, subtle within-CT genes). But to reemphasize - I dont really know how Harmony would perform, and it is a well-known batch correction method (which is ultimately what you want for the embedding for miloDE) - so it is very possible it will be completely fine. I personally often run MNN-corrected PCA (ensuring that HVGs were selected from control data only), and I’m generally satisfied with that.

I hope this answer clarifies a bit on how I recommend people think about embedding choices when they apply miloDE.

2. How filtering of neighbourhoods affects DE detection.
Filtering of neighbourhoods is potentially good not only for run time, but for detection as well. By a priori discarding neighbourhoods that are very likely to be of uninterest (and therefore likely to have high p-values), you mitigate the severity for multiple testing correction. In principle, we propose a way to identify neighbourhoods with ‘no signs of DE’ a priori, by adapting Augur (https://github.com/neurorestore/Augur) on a neighbourhood basis (`miloDE::calc_AUC_per_neighbourhood`). I want to emphasize though, that in the presence of batch effects (which is almost the case), unfortunately, using Augur we can not distinguish batch effect from potential DE, and after running this rather time-consuming part of the algorithm, you might end up with a very little gain (i.e. vast majority of the neighbourhoods will be selected for the downstream analysis - negligible gain in terms of multiple testing correction). But, to be fair, another class of neighbourhoods that our Augur-based neighbourhood selection identifies as inappropriate for DE testing - are neighbourhodos with very few cells in at least one condition which sometimes is very possible, so it might be useful. To put this confusing paragraph in a more detailed pipeline, I suggest the next approach toward neighbourhood selection.

before running DE testing itself, assess your data in 2 ways: 1 - do you anticipate batch effects in your data or rather not? 2 - do you observe a lot of highly DA neighbourhoods (say with less than 5-10 cells in at least one condition).
If you do not anticipate much batch effect - consider running nighbourhood selection: `miloDE::calc_AUC_per_neighbourhood`. You can use a standard cut-off of AUC of 0.5 to select neighbourhoods for follow-up DE testing.
If you anticipate batch effect but you see that you have quite a lot of neighbourhoods with very few cells in at least one condition - consider running a custom script that quickly scans those neighbourhoods and discards them from the DE testing (it will be much quicker than building Augur classifiers). Atm it is not supported in the main branch, but I consider adding it later and let me know if that's of interest, I can help drafting a script to do just that.
Finally, if you anticipate batch effect, as well as there, are not many imbalanced neighbourhoods - I think you can safely proceed to DE testing without any neighbourhood selection.


3. discrepancies between ‘bulk’ and ‘miloDE’ approaches.
Yeah, that is possible and in fact, thats the main reason we developed miloDE :) 
I guess there are maybe a few scenarios why this happens, but the one which we advocate is most likely and the advantage of miloDE is that it is much more sensitive than bulk method and is capable of detecting DE differences in very local regions of the manifold (sub-cell types to the most granular level). This is particularly relevant for continuous cell types so if this is your case, what you observe is not too far reached. 

If in your case the difference between ‘bulk’ and ‘miloDE’ seems overwhelming, I would recommend manually expecting miloDE results to provide more confidence in the results.

Few suggestions on what you can do:

you say you detect 2 modules that agree with expectations based on animal studies. Plot a few genes from the modules individually (you can use `miloDE::plot_DE_single_gene` as well as simply plot UMAPs colored by counts and faceted by conditions). Does this look like what you would expect based on the ‘module signature’?
In the modules signature plots - do neighbourhoods with high DE seem to be close to each other or are they rather sporadic? If they seem too sporadic - this is the sign of FP detection, but if they seem rather coherent and near by - then it is something interesting to investigate further (i.e. potentially relevant).
If the neighbourhoods cluster together and assume they are annotated within the same CT - what is the difference between the rest of the neighbourhoods of this CT? One way would be to select only reference data and perform DE detection between neighbourhoods (the ones that are flagged as very DE in miloDE VS the rest). Do you see some plausible biological markers that separate two groups of neighbourhoods? I believe that for this task you can use `miloR::findNhoodMarkers` is tailored to do something akin to what Im suggesting.
Finally, using these markers - can you further subcluster your cell type. If yes, do you now observe DE in the sub-cell type of where you expect it to see? If yes - this is the good sign that miloDE happened to be sensitive enough to pick the local sub-cell type difference that bulk DE missed.

4. Are miloDE::assign_neighbourhoods the same as miloR::buildGraphs and miloR::makeNhoods?
Almost, but not quite. Essentially, `miloDE::assign_neighbourhoods` is a wrapper for these 2 miloR functions, but with some additional tweaks/options: 
We allow (we actually encourage) the 2nd-order kNN graph assignment (the standard kNN is also possible, you need to select `order=1`).
We provide a neighbourhood refinement step.

In principle, you can use original Milos functions, but in this case, you need to force your `k`  to be rather big as well as you might end up with too many overlapping, sort of redundant, neighbourhoods. So I would encourage you to use miloDE’s assignment functions.


5. Conversion from Seurat for integrated assay.
Yeah, I can see how it is a little annoying. Tbh I’m surprised to see that counts are not converting to SCE. If you could share a toy Seurat ds for which it doesnt work, I could try it myself?
I can suggest that one (rather unelegant) workaround would be to rewrite your logcounts to counts in your Seurat object, and then perform the conversion. Since you are converting inetrgated object, I assume that your dimensionality reduction has been already calculated, and in this case you dont really need logcounts for miloDE.

**Comment by learning-MD** [comment]
Thanks @amissarova - that is an incredibly thorough response! I think Harmony should be okay to use, but I'll test out a couple of other strategies as well - mainly, I may just focus on 1) integrating together the control samples first followed by reference-mapping of the disease onto the controls and 2) not integrating samples in the first place (since, by visualization of the unintegrated samples, I cannot really make out a batch effect - samples were hashtagged, so it goes a long ways in minimizing batch effects). The latter is the reason why I think using the Harmony embeddings as I did is okay.

Trying to plot gene modules as you suggested, one issue I've run into with `plot_DE_single_gene` and `plot_DE_gene_set` is that I keep running into the following error that I'm having difficulty troubleshooting:

```
Error in .check_nhood_stat(nhood_stat, x) : 
  'nhood_stat$Nhood' should be within c(1:ncol(nhoods(x))).
```

Any suggestions there? Thanks.

**Comment by amissarova** [comment]
Also @learning-MD , I just realised that when you were asking about neighbourhood filtering, you might have meant filtering at the stage of neighbourhood assignment? In this case yeah, it is mainly for computing time (and on rather rare occasions it might help for multiple testing correction issue, but rarely so)

**Comment by amissarova** [comment]
@learning-MD , it is very hard for me to give a proper answer for the system I don't really know so I cant help you much w it. few random thoughts:
* I would say tho that module 1 looks rather random; module 2 looks more biologically meaningful. One way of having a confidence that module is meaningful is doing some funcgen on the genes - do they seem functionally related/good GO enrichment?
* I would also suggest for plotting reasons to set `edge_weight.thresh` to something (try 100) - so all the edges are not that overwhelming.
* Also, for gene clustering, consider Louvain? Please see the manuscript, chapter IPF - it is an inclusive clustering, so more genes will be in your clusters
* Given your data, I would probably suggest increasing k slightly - less nhoods, higher sensitivity, better detection

**Comment by learning-MD** [comment]
Thanks @amissarova - appreciate the guidance.

**Comment by mihem** [comment]
@amissarova just a friendly reminder of my last message in case you missed it because this issue is so busy. It was just yesterday, so please don't feel rushed.

**Comment by amissarova** [comment]
@mihem , I did see it  but I had other stuff on my plate and since it is not really a bug to be fixed but just an additional feature, I decided it could wait. I will respond later today

**Comment by amissarova** [comment]
Hey @mihem, 

1. I looked through your example on pancreas data. From what it seems to me (correct me if Im wrong), the problem here is that there are actually no raw counts in the very upstream `seu`: data and counts slot are the same (when usually one corresponds to counts and the other to logcounts), and they both floats (not integers like you would expect the counts). Accordingly there will be no raw counts in the integrated object.

```
mean(seu@assays$RNA@data == seu@assays$RNA@counts)
1
```
So I think it is possible that therefore they are not converted coz they don't exist. Do you perhaps have another example ds for which you are sure there are both counts and logcounts data available? I could try and look for them later, but if you have smth ready, that would be easier. Meanwhile I will try and find the example myself.

3. Why miloDE needs counts:
miloR is looking for DA abundance so virtually doesn't need any assays available but only dimRed together with cell numbers. In turn. miloDE is doing DE and relies on counts.
Therefore I introduced the check for the correct SCE format and this check includes checking for the counts slot. In reality, you are right - for the neighbourhood assignment you dont need to have counts slot (same as in miloR), but since it is required after, the function `assign_neighbourhoods` checks SCE in the same manner as for downstream functions. Hope that makes sense?

4. And even more that the author of Augur says that It's fine to use raw RNA counts as input. 
Yeah, i saw that Augur does that for the task (CT ranking). The thing tho is that I adapt Augur for a slightly different task and check different datasets between themselves - using logcounts in my opinion helps to mitigate different sequencing coverage for different datasets. Otherwise, you are much more likely to get AUC > 0.5

5. Vignette with Seurat. 
Well, essentially this vignette will boil down to conversion vignette between Seurat and SCE, and those already exist. 
The whole miloDE pipeline relies on SCE object, and the only think you need to do is convert Seurat. But since there seems to be a request, I will consider adding this vignette later on (but possibly not ASAP).

Mwanwhile I will try and find a valid seurat object to test for conversion issue you mentioned

**Comment by amissarova** [comment]
![Screenshot 2023-04-01 at 11 50 08](https://user-images.githubusercontent.com/24481648/229284687-c228b7f6-5ef5-43b2-92a6-49985a8fe9a4.png)

**Comment by amissarova** [comment]
@mihem , just fyi - i updated the comment response (originally I had it wrong just in case you saw the comment earlier) - please let me know if smth is unclear

**Comment by mihem** [comment]
@amissarova thanks again for your extensive reseponse.

I think we are making it a little bit more complicated than it is. I am working my own dataset, I just used this one because you asked to provide a toy example, and this is already available. I don't have a reference dataset, just a few samples that need to be integrated. Therefore, this Seurat tutorial is probably more approriate: https://satijalab.org/seurat/articles/integration_introduction.html

```
# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = ifnb.list)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)
```

I now want to use this immune.combined for miloDE.

**So the main question, which I still didn't get: If I use RNA, I have raw counts (assay RNA, slot count) and normalized counts (assay RNA, slot data), but they are not batch-corrected. Is this the right input for miloDE? I think your tutorial suggests that you need pca.corrected, which would be equivalent integrated assay (or harmony assay) in Seurat/Harmony? But then if I use the integrated assay only, raw counts are missing and we only haved 2000 top variable genes as you correctly say.**

In Lemur, the other tool that Rahul Satija advertised on Twitter next to miloDE, the author clearly states that you should not use harmony/integrate assay, but use the normalized data from Seurat and the  `align_harmony` from lemur https://github.com/const-ae/lemur/issues/2
In contrast, in miloR, Mike/Emma say that using any batch-corrected data is fine https://github.com/MarioniLab/miloR/issues/151. So for miloR you I just used the integrated assay and everything worked fine. But for miloDE this doesn't work because raw counts are required, which make sense for the DE analysis.

Sorry, you may have already answered this partially in your answer, but I couldn't follow your script from 

```
# now lets project pca from reference onto query samples and return SCE with calculated PCA
...
```
on. And again, there's no need for a reference dataset. Just the question, which assays are needed and how to convert a Seurat object with RNA and integrated assay correctly to a SCE object for the miloDE analysis.

Thank you !

**Comment by amissarova** [comment]
@mihem, 
In this case, you just need to:
1. (You are already doing it). Calculate PCA on your integrated Seurat object (I mean on the integrated assay) - this pca will be used as coordinates of embedding.
2. Move your Seurat to SCE with as.SingleCellExperiment(your_integrated_seurat, assay = “RNA”). This will have both raw counts for DE as well PCA reduced dimension slot for the embedding

**Comment by mihem** [comment]
Thanks.

Ah I understand. I thought that if you use 

`as.SingleCellExperiment(seu, assay = “RNA”)`

But you are right, PCA is included in that object and since PCA was only calculated on the integrated assay it's a batch-corrected assay. Maybe important note for other users of if you include that in your vignette. If you leave out `assay = RNA`, and just run `as.SingleCellExperiment(seu)`, PCA/UMAP are not included.
Sorry just one remaining question. What's the right way for miloR for DA analysis then? Also `as.SingleCellExperiment(seu, assay = “RNA”)`or integrated assay? Because unlike miloDE, miloR works fine without counts, but maybe it's still technically wrong? 

Thank you!

**Comment by amissarova** [comment]
@mihem,

as far as for the main part of miloR - neighbourhood assignment and estimation of DA - I'm pretty sure the only thing you need as your embedding and cell/sample composition - and then it shouldn't matter which assay you should use for miloR, from the integrated or RNA (I assume you are asking since you already perform your milo-analysis on integrated and you are wondering if you should re-do it -- I believe you don't; if you want another confirmation tho, you prob want to open an issue in miloR github).

But i should mention tho that there are other functions in milo for the downstream analysis (such as `findNhoodMarkers` for example but possibly more) - and for them you are required original logcounts or counts assay - so if you used this function on integrated assay from the conversion, you had your logcounts 'wrong' and you probably would need to re-do this part of the analysis.

**Comment by mihem** [comment]
@amissarova  
Thank you again.

I reran miloR with RNA assay (including PCA/UMAP based on integrated assay) and not integrated assay. I took much longer so I followed mike's advice and used `refinement_scheme = "graph"` in `makeNhoods` and `fdr.weighting = "graph-overlap"` in `testNhoods`. Results were similar but I got more neighbourhoods

So i close this issue now, thanks again.
For the vignette: Seurat users need to remember to explicitly name the `assay` argument in `as.SingleCellExperiment` and use the RNA assay.

**Comment by mihem** [comment]
sorry for necrobumping: just one additional comment for future me and other users:

If you use Harmony instead of Seurat CCA for batch removal, PCA is NOT batch-corrected. Then HARMONY should be used in 
`assing_neighbourhoods` as `reducedDim_name` I think.
